apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mywebapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/a-mckeown/cncf-pbf.git
    targetRevision: HEAD
    path: "."
  destination:
    server: https://kubernetes.default.svc
    namespace: mywebapp
  syncPolicy:
    syncOptions:
    - CreateNameSpace=true
    automated:
      selfHeal: false
      prune: false

  
